---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: Template to produce a light weight imagestream and buildconfig for a multistage build
  name: multistage-build-template
parameters:
- description: .
  name: INTERMEDIATE_IMAGE
  value: quay.io/jdowland/jlink:ubi9-jlinked-image
  required: true
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: lightweight-image
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata: 
    name: multistage-buildconfig
  spec:
    source:
     type: Dockerfile
     dockerfile: |
        FROM ${INTERMEDIATE_IMAGE} AS ubi9-jlinked-image
        USER 0
        RUN mkdir -p /mnt/jrootfs
        RUN microdnf install --installroot /mnt/jrootfs --releasever 9 --setopt install_weak_deps=0 --nodocs -y \
            --config=/etc/dnf/dnf.conf \
            --noplugins \
            --setopt=cachedir=/var/cache \
            --setopt=reposdir=/etc/yum.repos.d \
            --setopt=varsdir=/etc/dnf/vars \
            grep gawk
        RUN rm -rf /mnt/jrootfs/var/cache/* /mnt/jrootfs/var/lib/rpm /mnt/jrootfs/var/lib/dnf

        #Stage-2:copy application JAR and jlinked JRE to runtime image
        FROM registry.access.redhat.com/ubi9/ubi-micro AS lean-runtime
        ARG JAVA_HOME=/usr/lib/jvm/java

        COPY --from=ubi9-jlinked-image /mnt/jrootfs/ /
        COPY --from=ubi9-jlinked-image /deployments /deployments
        COPY --from=ubi9-jlinked-image /tmp/jre ${JAVA_HOME}
        COPY --from=ubi9-jlinked-image /opt/jboss/container/ /opt/jboss/container/
        # these are in the micro image
        RUN rm -rf /var/lib/dnf /var/lib/rpm

        ENV JAVA_HOME="${JAVA_HOME}" PATH="${JAVA_HOME}/bin:$PATH"
        USER 185
        CMD /opt/jboss/container/java/run/run-java.sh
    strategy:
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: lightweight-image:latest  # Tag for the final output image
    triggers:
      - type: ConfigChange
